version: "2"
services:
  requisition-ui:
    image: openlmis/dev-ui:9.0.0
    working_dir: /app
    volumes:
      - '.:/app'
    ports:
      - "9000:9000"
      - "9876:9876"
    env_file: .env
    volumes_from:
      - auth-ui
      - referencedata-ui
      - stockmanagement-ui
      - ui-components
      - ui-layout
    depends_on:
      - auth-ui
      - referencedata-ui
      - stockmanagement-ui
      - ui-components
      - ui-layout
  auth-ui:
    image: openlmis/auth-ui:6.2.1-RC1
    volumes:
      - '/openlmis-auth-ui'
  fulfillment-ui:
    image: openlmis/fulfillment-ui:6.0.4-RC1
    volumes:
      - '/openlmis-fulfillment-ui'
  referencedata-ui:
    image: openlmis/referencedata-ui:5.6.0-RC1
    volumes:
      - '/openlmis-referencedata-ui'
  stockmanagement-ui:
    image: openlmis/stockmanagement-ui:2.0.4-RC1
    volumes:
     - '/openlmis-stockmanagement-ui'
  ui-components:
    image: openlmis/ui-components:7.2.0-RC1
    volumes:
      - '/openlmis-ui-components'
  ui-layout:
    image: openlmis/ui-layout:5.1.4-RC1
    volumes:
      - '/openlmis-ui-layout'
  image:
    build: .
    image: openlmis/requisition-ui
